# Generated by Django 5.1.2 on 2024-10-22 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_vote_ratio_alter_project_vote_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='decription',
            new_name='description',
        ),
    ]
